DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field# Default primary key field typeSTATIC_URL = '/static/'# https://docs.djangoproject.com/en/3.2/howto/static-files/# Static files (CSS, JavaScript, Images)USE_TZ = TrueUSE_L10N = TrueUSE_I18N = TrueTIME_ZONE = 'UTC'LANGUAGE_CODE = 'en-us'# https://docs.djangoproject.com/en/3.2/topics/i18n/# Internationalization]    },        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',    {    },        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',    {    },        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',    {    },        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',    {AUTH_PASSWORD_VALIDATORS = [# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators# Password validation}    }        'NAME': BASE_DIR / 'db.sqlite3',        'ENGINE': 'django.db.backends.sqlite3',    'default': {DATABASES = {# https://docs.djangoproject.com/en/3.2/ref/settings/#databases# DatabaseWSGI_APPLICATION = 'octofit_tracker.wsgi.application']    },        },            ],                'django.contrib.messages.context_processors.messages',                'django.contrib.auth.context_processors.auth',                'django.template.context_processors.request',                'django.template.context_processors.debug',            'context_processors': [        'OPTIONS': {        'APP_DIRS': True,        'DIRS': [],        'BACKEND': 'django.template.backends.django.DjangoTemplates',    {TEMPLATES = [ROOT_URLCONF = 'octofit_tracker.urls']    'django.middleware.clickjacking.XFrameOptionsMiddleware',    'django.contrib.messages.middleware.MessageMiddleware',    'django.contrib.auth.middleware.AuthenticationMiddleware',    'django.middleware.csrf.CsrfViewMiddleware',    'django.middleware.common.CommonMiddleware',    'django.contrib.sessions.middleware.SessionMiddleware',    'django.middleware.security.SecurityMiddleware',MIDDLEWARE = []    'tracker',    'django.contrib.staticfiles',    'django.contrib.messages',    'django.contrib.sessions',    'django.contrib.contenttypes',    'django.contrib.auth',    'django.contrib.admin',INSTALLED_APPS = [# Application definitionALLOWED_HOSTS = ['*']  # Permitir todos os hosts para desenvolvimentoDEBUG = True# SECURITY WARNING: don't run with debug turned on in production!SECRET_KEY = 'django-insecure-4!@#%&*()_+'# SECURITY WARNING: keep the secret key used in production secret!# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/# Quick-start development settings - unsuitable for productionBASE_DIR = Path(__file__).resolve().parent.parent# Build paths inside the project like this: BASE_DIR / 'subdir'.from pathlib import Path"""https://docs.djangoproject.com/en/3.2/ref/settings/For the full list of settings and their values, seehttps://docs.djangoproject.com/en/3.2/topics/settings/For more information on this file, seeGenerated by 'django-admin startproject' using Django 3.2.5.Django settings for octofit_tracker project.Django settings for octofit_tracker project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!